# Generated by Django 4.1.7 on 2023-05-05 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flipcart", "0004_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("mobile", models.BigIntegerField(blank=True, default=0, null=True)),
                ("price", models.BigIntegerField(blank=True, default=0, null=True)),
                ("quantity", models.BigIntegerField(blank=True, default=0, null=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flipcart.product",
                    ),
                ),
            ],
        ),
    ]
